# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a3641fcb6eb95079da1d1c1e8e247b6d4fab47e00edb14af8d5b20691d2fad0ff336b5709111eb650790dd509fe8b838f31621e7f958e95a63f36653dc285a8

test:
  secret_key_base: a6781c55ae5f968da3f5a033ca5fbaae7157825ac23bb9eee9cfb6af5d40633dc7520c01b2a85f88b14cc00ad75ab291fd5ff640dd3ff00fd42587c082138858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
